_target_: dataset.hand_dataset.FreiHANDDataset

opt:
  image: 
    path: "data/FreiHAND/evaluation/rgb/%08d.jpg"

  hand: 
    hifihr_pretrained: "assets/hifihr/full_freihand.t7"
    mano_model: "assets/mano/MANO_RIGHT.pkl"
    nimble: True
    nimble_pm_dict: "assets/nimble/NIMBLE_DICT_9137.pkl"
    nimble_mano_vreg: "assets/nimble/NIMBLE_MANO_VREG.pkl"
    nimble_tex_fuv: "assets/nimble/NIMBLE_TEX_FUV.pkl"
    arm: False
    smplx_model: "assets/smplx/SMPLX_NEUTRAL.pkl"
    smplx_arm_corr: "assets/smplx/smplx_arm_corr.pkl"
  
  cached:
    image:
      inpainted_path: "data/FreiHAND/evaluation/inpainted/%08d.jpg"
      # intrinsics: "/dev/hdd/HiFiHR/outputs/freihand/evaluation_final/obj/test/demo_eval_0560_%07d_Ks.npy"
      handarm_seg: "data/FreiHAND/evaluation/pred_twohands/%08d.png" 
      object_seg: "data/FreiHAND/evaluation/pred_obj1/%08d.png"
    hand:
      path: "data/FreiHAND/evaluation/hifihr_obj/%07d.obj"
      xyz: "data/FreiHAND/evaluation/hifihr_obj/%07d_pred_xyz.npy"  #"data/FreiHAND/evaluation_xyz.json"