_target_: dataset.hand_dataset.FreiHANDDataset

opt:
  refresh: True

  image: 
    path: "data/FreiHAND/evaluation/rgb_SR/%08d.png"
    mediapipe: "assets/mediapipe/hand_landmarker.task"
    sam: "assets/sam/sam_vit_h_4b8939.pth"

  hand: 
    hifihr_pretrained: "assets/hifihr/full_freihand.t7"
    mano_model: "assets/mano/MANO_RIGHT.pkl"
    nimble: True
    nimble_pm_dict: "assets/nimble/NIMBLE_DICT_9137.pkl"
    nimble_mano_vreg: "assets/nimble/NIMBLE_MANO_VREG.pkl"
    nimble_tex_fuv: "assets/nimble/NIMBLE_TEX_FUV.pkl"
    arm: False
    smplx_model: "assets/smplx/SMPLX_NEUTRAL.pkl"
    smplx_arm_corr: "assets/smplx/smplx_arm_corr.pkl"
  
  cached:
    image:
      seg: "data/FreiHAND/evaluation/sam_seg/%08d.png"
      seg_vis: "data/FreiHAND/evaluation/sam_seg/vis_%08d.png"
      inpainted: "data/FreiHAND/evaluation/inpainted/%08d.jpg"
    hand:
      path: "data/FreiHAND/evaluation/hifihr_obj/%07d.obj"
      xyz: "data/FreiHAND/evaluation/hifihr_obj/%07d_pred_xyz.npy"
    mano_r:
      path: "data/FreiHAND/evaluation/hifihr_obj/%07d_r.obj"  
      joint: "data/FreiHAND/evaluation/hifihr_obj/%07d_r_joints.npy"
      joint_vis: "data/FreiHAND/evaluation/hifihr_obj/%07d_r_joints_vis.ply"
      bone_vis: "data/FreiHAND/evaluation/hifihr_obj/%07d_r_bone_vis.ply"