Niters: 2000
lr: 0.1

plot:
  log_period: 100
  mesh_period: 100
  pc_period: 1000000
  contact_period: 1000000

loss:
  attraction_weight: 0.1
  repulsion_weight: 0.9

contactloss:
  contact_thresh: 5
  contact_mode: "dist_tanh"
  collision_thresh: 10
  collision_mode: "dist_tanh"
  contact_target: "obj"
  contact_sym: False
  contact_zones: "zones"