blend_type: "alpha_blending"  # choice: alpha_blending, poisson

inpaint:
  _target_: visualization.inpaint.Inpainter
  opt:
    hand_type: "mask" # choice: point, mask
    object_type: "point"  # choice: point, mask
    mask_dilate_size: 15
    sam:
      model_type: "vit_h"
      ckpt: "assets/sam/sam_vit_h_4b8939.pth"
      mask_idx: 2
    lama:
      config_file: "assets/lama/default.yaml"
      ckpt: "assets/lama/big-lama"