_target_: dataset.datasets.ManualDataset

opt:
  hand:
    path: "/dev/hdd/hamer/demo_out/test2_1.obj"
  
  object:
    path: "/dev/hdd/contactgen/exp/demo_results/toothpaste.ply"  #  "/dev/hdd/YCB/031_spoon/google_16k/textured.obj"
    sampled_verts_path: "/dev/hdd/contactgen/exp/demo_results/obj_verts_7.npy"
    contacts_path: "/dev/hdd/contactgen/exp/demo_results/contacts_7.npy"
    partitions_path: "/dev/hdd/contactgen/exp/demo_results/partition_7.npy"