inpaint:
  _target_: visualization.inpaint.Inpainter
  opt:
    hand_type: "mask" # choice: point, mask
    object_type: "point"  # choice: point, mask
    mask_dilate_size: 15
    sam:
      model_type: "vit_h"
      ckpt: "submodules/Inpaint_Anything/pretrained_models/sam_vit_h_4b8939.pth"
      mask_idx: 2
    lama:
      config_file: "submodules/Inpaint_Anything/lama/configs/prediction/default.yaml"
      ckpt: "submodules/Inpaint_Anything/pretrained_models/big-lama"