defaults:
  - dataset/hand@hand_dataset: freihand
  - dataset/object@object_dataset: ycb
  - module/optimize_object@optimize_object: obman
  - module/reconstruct_hand@reconstruct_hand: hifihr
  - vis: visualize
  - metric: metric
  - _self_

debug: True
test_only: False
devices: [0]

resume_dir: ''
output_dir: ???   # will be set automatically
results_dir: ???  # will be set automatically
ckpt_dir: ???     # will be set automatically

hydra:
  job:
    chdir: False 
  
  job_logging:
    root:
      level: INFO