defaults:
  - dataset/hand@hand_dataset: freihand
  - dataset/object@object_dataset: ycb
  - dataset/selector@selector_dataset: dexycb

  - module/reconstruct_hand@reconstruct_hand: hifihr
  - module/select_object@select_object: cvae
  - module/testtime_optimize@testtime_optimize: obman
  
  - vis: visualize
  - metric: metric
  - _self_


debug: True
object_selector: 'inference'  # 'train' or 'inference'
is_preoptimized: False

devices: [0]
batch_size: 1

resume_dir: ''
selector_ckpt: '/dev/hdd/GenHeld/outputs/2024-03-25/01-26-10/selector_checkpoints/epoch=151-step=456.ckpt'

# Don't touch the ???
output_dir: ??? 
results_dir: ???
selector_ckpt_dir: ???
ckpt_dir: ???   

hydra:
  job:
    chdir: False 
    
  job_logging:
    root:
      level: INFO