defaults:
  # - dataset: manually
  - dataset/hand@hand_dataset: freihand
  - dataset/object@object_datsaet: ycb
  - optimization: obman
  - vis: visualize
  - _self_

debug: True

results_dir: ??? 

hydra:
  job:
    chdir: False 