# Don't touch the ???

defaults:
  - dataset/hand@hand_dataset: freihand
  - dataset/object@object_dataset: objaverse
  - dataset/selector@selector_dataset: dexycb

  - module/reconstruct_hand@reconstruct_hand: hifihr
  - module/select_object@select_object: shapecode
  - module/testtime_optimize@tta: obman
  
  - vis: visualize
  - metric: metric
  - _self_


debug: False
batch_size: 1
devices: [0]

selector: 
  mode: 'inference'  # 'train' or 'inference'
  ckpt_dir: ???
  ckpt_path: 'assets/selector_checkpoints/epoch=341-step=1026.ckpt'

optimizer:
  mode: 'optimize'  # 'optimize' or 'evaluate'
  resume_dir: ''


output_dir: ??? 
results_dir: ???
ckpt_dir: ???   

hydra:
  job:
    chdir: False 
    
  job_logging:
    root:
      level: DEBUG