n_obj: 4
n_iters: 3500
scale_clip: [0.9, 1.02]
start_fidx: 84
end_fidx: 500

lr_init: 0.1
lr_type: "StepLR"
lr_params:
  step_size: 500
  gamma: 0.8

plot:
  tolerance_step: 200 # 300
  tolerance_difference: 0.0003
  mesh_period: 10000
  render_period: 10000
  render_eval: True
  pc_period: 1000000
  force_closure_period: 100000
  contact_period: 1000000

loss:
  attraction_weight: 0.7
  repulsion_weight: 1.0
  force_closure_weight: 0.005

contactloss:
  contact_file: "assets/contact_zones.json"
  contact_thresh: 5
  contact_mode: "dist_tanh"
  collision_thresh: 10
  collision_mode: "dist_tanh"
  contact_target: "obj"
  contact_sym: False
  contact_zones: "zones"
  fc_n_contacts: 3
  fc_voxel_size: 0.01