Niters: 1000
lr: 0.1

plot:
  tolerance_step: 200
  tolerance_difference: 0.0005
  mesh_period: 10000
  render_period: 10000
  pc_period: 1000000
  contact_period: 1000000

loss:
  attraction_weight: 0.5
  repulsion_weight: 0.5

contactloss:
  contact_thresh: 5
  contact_mode: "dist_tanh"
  collision_thresh: 10
  collision_mode: "dist_tanh"
  contact_target: "obj"
  contact_sym: False
  contact_zones: "zones"