_target_: module.select_object.SelectObject

opt:
  n_class: 21
  Nepochs: 1000
  lr: 0.0005
  weight_decay: 0.0005

  dim_hand_pose: 48
  dim_hand_verts: 778
  dim_latent: 16
  
  train:
    batch_size: 40
    n_vis_samples: 4
    vis_epoch: 100
    debug_vis_epoch: 100
  val:
    ratio: 0.2
    period: 50
    vis_epoch: 50
    debug_vis_epoch: 200

  loss: 
    kl_weight: 0.01
    kl_annealing_epoch: 50 
    category_weight: 1
    objectpoint_weight: 0.1
    contact_weight: 0.1
    consistency_weight: 0.05

  category:
    hc: 512

  object:
    hc: 64
    points: 7569

  fusion:
    hc: 512