_target_: module.select_object.SelectObject

opt:
  n_class: 6
  n_obj_points: 3000
  dim_hand_pose: 48
  
  train:
    batch_size: 40
    Nepochs: 9000
    lr: 0.0005
    weight_decay: 0.0005
    vis_samples: 4
    vis_epoch: 100
    vis_debug_epoch: 100

  val:
    n_per_class: 1
    period: 50
    vis_epoch: 50
    vis_debug_epoch: 200

  loss: 
    kl_weight: 0.01
    kl_annealing_epoch: 50 
    category_weight: 1
    objectpoint_weight: 0.5
    contact_weight: 0.1
    consistency_weight: 0.0