Niters: 1000
lr: 0.05
hand_batch: 1
obj_batch: 1

plot:
  log_period: 100
  mesh_period: 100
  render_period: 100
  pc_period: 1000000
  contact_period: 100

loss:
  attraction_weight: 0.5
  repulsion_weight: 0.5

contactloss:
  contact_thresh: 5
  contact_mode: "dist"
  collision_thresh: 10
  collision_mode: "dist_tanh"
  contact_target: "obj"
  contact_sym: False
  contact_zones: "gen"